# Generated by Django 3.0.7 on 2020-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=64)),
                ('age', models.CharField(max_length=512)),
                ('eye_color', models.CharField(max_length=512)),
                ('hair_color', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=512, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('director', models.CharField(blank=True, max_length=512)),
                ('producer', models.CharField(blank=True, max_length=512)),
                ('release_date', models.CharField(blank=True, max_length=512)),
                ('rt_score', models.CharField(blank=True, max_length=512)),
                ('people', models.ManyToManyField(to='server.People')),
            ],
        ),
    ]
